.TH MSTCONFIG "1" "4.6.0"  "10 January 2017" ""
.SH NAME
mstconfig
.IP
.SH SYNOPSIS:
.IP
mstconfig [Options] <Commands> [Parameters]
.IP
.SH OPTIONS:
.RS
.TP
.B
\fB-d\fP|\fB--dev\fP <device>
: Perform operation for a specified MST device.
.TP
.B
\fB-b\fP|\fB--db\fP <filename>
: Use a specific database file.
.TP
.B
\fB-f\fP|\fB--file\fP <conf_file>
: raw configuration file.
.TP
.B
\fB-h\fP|\fB--help\fP
: Display help message.
.TP
.B
\fB-v\fP|\fB--version\fP
: Display version info.
.TP
.B
\fB-e\fP|\fB--enable_verbosity\fP
: Show default and current configurations.
.TP
.B
\fB-y\fP|\fB--yes\fP
: Answer yes in prompt.
.TP
.B
\fB-a\fP|\fB--all_attrs\fP
: Show all attributes in the XML template
.RE
.PP
.SH COMMANDS:
.RS
.TP
.B
clear_semaphore
: clear the tool semaphore.
.TP
.B
i[show_confs]
: display informations about all configurations.
.TP
.B
q[uery]
: query supported configurations.
.TP
.B
r[eset]
: reset all configurations to their default value.
.TP
.B
s[et]
: set configurations to a specific device.
.TP
.B
set_raw
: set raw configuration \fBfile.\fP(only Connect-IB/Connect-X4/LX.)
.TP
.B
backup
: backup configurations to a \fBfile.\fP(only Connect-IB/Connect-X4/LX.). Use set_raw command to restore file.
.TP
.B
gen_tlvs_file
: Generate List of all TLVs. TLVs output file name must be specified. (*)
.TP
.B
g[en_xml_template]
: Generate XML template. TLVs input file name and XML output file name must be specified. (*)
.TP
.B
xml2raw
: Generate Raw file from XML file. XML input file name and raw output file name must be specified. (*)
.TP
.B
raw2xml
: Generate XML file from Raw file. raw input file name and XML output file name must be specified. (*)
.RE
.PP
(*) These commands do not require MST device
.PP
To show supported configurations by device type, run show_confs command
.RE
.RE
.PP

.RS
Examples:
.RS
.TP
.B
To query configurations
: mstconfig \fB-d\fP 04:00.0 query
.TP
.B
To set configuration
: mstconfig \fB-d\fP 04:00.0 set SRIOV_EN=1 NUM_OF_VFS=16 WOL_MAGIC_EN_P1=1
.TP
.B
To set raw configuration
: mstconfig \fB-d\fP 05:00.0 \fB-f\fP conf_file set_raw
.TP
.B
To reset configuration
: mstconfig \fB-d\fP 04:00.0 reset
.RE
.PP
Supported devices:
4th Generation devices: ConnectX3, ConnectX3-Pro (FW 2.31.5000 and above).
5th Generation devices: ConnectIB, ConnectX4, ConnectX4-LX, ConnectX5.
.PP
Note: query device to view supported configurations by Firmware.
