.TH mstflint "1" "4.6.0"  "10 January 2017" ""
.SH NAME
\fBmstflint \fP- Flash Interface
.SH SYNOPSIS
.nf
.fam C
  \fBMstFlint\fP [\fIOPTIONS\fP] <command> [\fIParameters\fP]
      [\fB-d\fP|\fB--device\fP <device>] [\fB-i\fP|\fB--image\fP <image>]
      [\fB-h\fP|\fB--help\fP] [\fB--hh\fP] [\fB-y\fP|\fB--yes\fP] [\fB--no\fP]
      [\fB--guid\fP <GUID>] [\fB--guids\fP <GUIDS\.\.\.>]
      [\fB--mac\fP <MAC>] [\fB--macs\fP <MACs\.\.\.>]
      [\fB--uid\fP <UID>] [\fB--blank_guids\fP] [\fB--clear_semaphore\fP]
      [\fB--qq\fP] [\fB--nofs\fP] [\fB--allow_psid_change\fP]
      [\fB--allow_rom_change\fP] [\fB--override_cache_replacement\fP]
      [\fB--no_flash_verify\fP] [\fB--use_fw\fP] [\fB-s\fP|\fB--silent\fP]
      [\fB--vsd\fP <string>] [\fB--use_image_ps\fP]
      [\fB--use_image_guids\fP] [\fB--use_image_rom\fP]
      [\fB--use_dev_rom\fP] [\fB--ignore_dev_data\fP]
      [\fB--dual_image\fP] [\fB--striped_image\fP]
      [\fB--banks\fP <bank>] [\fB--log\fP <log_file>]
      [\fB--flash_params\fP <type, log2size, num_of_flashes>]
      [\fB-v\fP|\fB--version\fP] 
.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
\fBMstFlint\fP [\fIOPTIONS\fP] <command> [\fIParameters\fP]
flint is a FW (firmware) burning and flash memory operations tool for
Mellanox Infiniband HCAs, Ethernet NIC cards, and switch devices.
.SH OPTIONS
\fBMstFlint\fP [\fIOPTIONS\fP] <command> [\fIParameters\fP]
.RS
.TP
.B
\fB-d\fP|\fB--device\fP <device>
: Device flash is connected to.
Commands affected: all
.TP
.B
\fB-i\fP|\fB--image\fP <image>
: Binary image file.
Commands affected: burn, verify
.TP
.B
\fB-h\fP|\fB--help\fP
: Prints this message and exits
.TP
.B
\fB--hh\fP
: Prints extended command help
.TP
.B
\fB-y\fP|\fB--yes\fP
: Non interactive mode - assume answer
"yes" to all questions.
Commands affected: all
.TP
.B
\fB--no\fP
: Non interactive mode - assume answer
"no" to all questions.
Commands affected: all
.TP
.B
\fB--guid\fP <GUID>
: GUID base value. 4 GUIDs
are automatically assigned to the following 
values:
.RS
.TP
.B
guid
-> node GUID
guid+1 -> port1
guid+2 -> port2
guid+3 -> system image GUID.
.PP
Note: port2 guid will be assigned even 
for a
single port HCA - The HCA ignores this value.
.PP
Commands affected: burn, sg
.RE
.TP
.B
\fB--guids\fP <GUIDS\.\.\.>
: 4 GUIDs must be specified here.
The specified GUIDs are assigned
to the following fields, respectively:
node, port1, port2 and system image GUID.
.RS
.PP
Note: port2 guid must be specified even 
for a
single port HCA - The HCA ignores this value.
It can be set to 0x0.
.PP
Commands affected: burn, sg
.RE
.TP
.B
\fB--mac\fP <MAC>
: MAC address base value. 2 MACs
are automatically assigned to the
following values:
.RS
.TP
.B
mac
-> port1
.TP
.B
mac+1
-> port2
.PP
Commands affected: burn, sg
.RE
.TP
.B
\fB--macs\fP <MACs\.\.\.>
: 2 MACs must be specified here.
The specified MACs are assigned
to port1, port2, respectively.
Commands affected: burn, sg
.RS
.PP
Note: \fB-mac\fP/\fB-macs\fP flags are applicable only 
for Mellanox
Technologies ethernet products.
.RE
.TP
.B
\fB--uid\fP <UID>
: ConnectIB/SwitchIB only. Derive and set the 
device UIDs (GUIDs, MACs, WWNs).
UIDs are derived from the given base UID 
according to Mellanox Methodology
Commands affected: burn, sg
.TP
.B
\fB--blank_guids\fP
: Burn the image with blank GUIDs and MACs 
(where
applicable). These values can be 
set later using
the "sg" command (see details below).
.RS
.PP
Commands affected: burn
.RE
.TP
.B
\fB--clear_semaphore\fP
: Force clear the flash semaphore on the device.
No command is allowed when this flag is 
used.
NOTE: May result in system instability 
or flash
corruption if the device or another
application is currently using the flash.
Exercise caution.
.TP
.B
\fB--qq\fP
: Run a quick query. When specified, flint 
will not perform full
image integrity checks during the query 
operation. This may shorten
execution time when running over slow interfaces 
(e.g., I2C, MTUSB-1).
Commands affected: burn, query
.TP
.B
\fB--nofs\fP
: Burn image in a non failsafe manner.
.TP
.B
\fB--allow_psid_change\fP
: Allow burning a FW image with a different 
PSID (Parameter Set ID)than the
one currently on flash. Note that changing 
a PSID may cause the device to
malfunction. Use only if you know what you 
are doing
.TP
.B
\fB--allow_rom_change\fP
: Allow burning/removing a ROM to/from FW image 
when product version is present.
Use only if you know what you are doing
.TP
.B
\fB--override_cache_replacement\fP
: On SwitchX/ConnectIB devices:
Allow accessing the flash even if the cache 
replacement mode is enabled.
NOTE: This flag is intended for advanced 
users only.
Running in this mode may cause the firmware 
to hang.
.TP
.B
\fB--no_flash_verify\fP
: Do not verify each write on the flash.
.TP
.B
\fB--use_fw\fP
: Flash access will be done using FW (ConnectX-3/ConnectX-3Pro 
only).
.TP
.B
\fB-s\fP|\fB--silent\fP
: Do not print burn progress flyer.
Commands affected: burn
.TP
.B
\fB--vsd\fP <string>
: Write this string, of up to 208 characters, 
to VSD when burn.
.TP
.B
\fB--use_image_ps\fP
: Burn vsd as appears in the given image - 
do not keep existing VSD on flash.
Commands affected: burn
.TP
.B
\fB--use_image_guids\fP
: Burn (guids/macs) as appears in the given 
image.
Commands affected: burn
.TP
.B
\fB--use_image_rom\fP
: Do not save the ROM which exists in the device.
Commands affected: burn
.TP
.B
\fB--use_dev_rom\fP
: Save the ROM which exists in the device.
Commands affected: burn
.TP
.B
\fB--ignore_dev_data\fP
: Do not attempt to take device data sections 
from \fBdevice\fP(sections will be taken from 
the image. FS3 Only).
Commands affected: burn
.TP
.B
\fB--dual_image\fP
: Make the burn process burn two images on 
flash (previously default algorithm). Currentdefault 
failsafe burn process burns a single image 
(in alternating locations).
Commands affected: burn
.TP
.B
\fB--striped_image\fP
: Use this flag to indicate that the given 
image file is in a "striped image" format.
Commands affected: query verify
.TP
.B
\fB--banks\fP <bank>
: Set the number of attached flash devices 
(banks)
.TP
.B
\fB--log\fP <log_file>
: Print the burning status to the specified 
log file
\fB--flash_params\fP <type, log2size, num_of_flashes>: Use the given parameters to access the flash 
instead of reading them from the flash.
Supported parameters:
Type: The type of the flash, such as:M25PXxx, 
M25Pxx, N25Q0XX, SST25VFxx, W25QxxBV, W25Xxx, 
AT25DFxxx, S25FLXXXP, S25FL11xx, MX25L16xxx.
log2size: The log2 of the flash size.num_of_flashes: 
the number of the flashes connected to the 
device.
.TP
.B
\fB-v\fP|\fB--version\fP
: Version info.
.RE
.RE
.PP
COMMANDS SUMMARY:
.RS
.TP
.B
burn|b
: Burn flash
.TP
.B
query|q [full]
: Query misc. flash/firmware characteristics, use "full"
to get more information.
.TP
.B
verify|v [showitoc]
: Verify entire flash, use "showitoc" to see ITOC headers
in FS3/FS4 image only.
.TP
.B
swreset
: SW reset the target un-managed switch device. This command
is supported only in the In-Band access method.
.TP
.B
brom
<ROM-file>                          : Burn the specified ROM file on the flash.
.TP
.B
drom
: Remove the ROM section from the flash.
.TP
.B
rrom
<out-file>                          : Read the ROM section from the flash.
.TP
.B
bb
: Burn Block - Burns the given image as is. No checks are done.
.TP
.B
sg
[guids_num=<num|num_port1,num_port2> step_size=<size|size_port1,size_port2>] | [nocrc] : Set GUIDs.
.TP
.B
sv
: Set the VSD.
.TP
.B
ri
<out-file>                            : Read the fw image on the flash.
.TP
.B
dc
[out-file]                            : Dump Configuration: print fw configuration file for the given image.
.TP
.B
dh
[out-file]                            : Dump Hash: dump the hash if it is integrated in the FW image
.TP
.B
set_key
[key]                            : Set/Update the HW access key which is used to enable/disable access to HW.
The key can be provided in the command line or interactively typed after
the command is given
NOTE: The new key is activated only after the device is reset.
.TP
.B
hw_access
<enable|disable> [key]         : Enable/disable the access to the HW.
The key can be provided in the command line or interactively typed after
the command is given
.TP
.B
hw
query                                 : Query HW info and flash attributes.
.TP
.B
erase|e <addr>
: Erases sector.
.TP
.B
rw
<addr>                                : Read one dword from flash
.TP
.B
ww
<addr> <data>                         : Write one dword to flash
.TP
.B
wwne
<addr> <data>                       : Write one dword to flash without sector erase
.TP
.B
wbne
<addr> <size> <data \.\.\.>            : Write a data block to flash without sector erase.
.TP
.B
wb
<data-file> <addr>                    : Write a data block to flash.
.TP
.B
rb
<addr> <size> [out-file]              : Read  a data block from flash
.TP
.B
clear_semaphore
: Clear flash semaphore.
.TP
.B
qrom
: query ROM image.
.TP
.B
checksum|cs
: perform MD5 checksum on FW.
timestamp|ts <set|query|reset> [timestamp] [FW version] : FW time stamping.
.TP
.B
cache_image|ci
: cache FW \fBimage\fP(Windows only).
.PP
Return values:
0 - Successful completion
1 - An error has occurred
7 - For burn command - FW already updated - burn was aborted.
