.TH MSTMTSERVER "1" "4.6.0" ""
.SH NAME
mstmtserver
.IP
.SH SYNOPSIS:
.IP
mstmtserver [options]
.IP
.SH OPTIONS:
.TP
\fB-p\fR[ort] <port> - Listen to specify port (default is 23108).
.TP
\fB-d\fR[ebug]       - Print all socket traffic (for debugging only).
.TP
\fB-h\fR[elp]        - Print help message.
.TP
