#######################################################
# 
# CapabilityFetcher.py
# Python implementation of the Class CapabilityFetcher
# Generated by Enterprise Architect
# Created on:      14-Aug-2019 10:12:01 AM
# Original author: talve
# 
#######################################################


class CapabilityFetcher:
    """this class responsible for fetching the core dump capability.
    """
    @classmethod
    def fetch(cls):
        """this method responsible for fetching the core dump capability
           and return it to the caller.
        """
        # return value from  regaccess, implementation is missing due to a fw bug
        return 2097152
