#ifndef DEVICE_TYPE_DETECTOR_DEFS_H
#define DEVICE_TYPE_DETECTOR_DEFS_H

#define MELLANOX_VENDOR_ID 0x15b3
#define MELLANOX_INTERNAL_HOST_PCI_ADDRESS "0000:00:00.0"

#define PCI_EXPRESS_UPSTREAM_PORT 0x5
#endif // DEVICE_TYPE_DETECTOR_DEFS_H