/*
 * Copyright (c) 2013-2024 NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED
 *
 * This software is available to you under a choice of one of two
 * licenses.  You may choose to be licensed under the terms of the GNU
 * General Public License (GPL) Version 2, available from the file
 * COPYING in the main directory of this source tree, or the
 * OpenIB.org BSD license below:
 *
 *     Redistribution and use in source and binary forms, with or
 *     without modification, are permitted provided that the following
 *     conditions are met:
 *
 *      - Redistributions of source code must retain the above
 *        copyright notice, this list of conditions and the following
 *        disclaimer.
 *
 *      - Redistributions in binary form must reproduce the above
 *        copyright notice, this list of conditions and the following
 *        disclaimer in the documentation and/or other materials
 *        provided with the distribution.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *  Version: $Id$
 *
 */

#ifndef H_BITS_HCA_CAP_TYPES_ADB_H
#define H_BITS_HCA_CAP_TYPES_ADB_H


enum {
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_GENERAL_DEVICE_CAPABILITIES           = 0x0,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ETHERNET_OFFLOAD_CAPABILITIES         = 0x1,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ODP_CAPABILITIES                      = 0x2,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ATOMIC_CAPABILITIES                   = 0x3,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ROCE_CAPABILITIES                     = 0x4,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_IPOIB_BASIC_OFFLOAD_CAPABILITIES      = 0x5,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_IPOIB_ENHANCED_OFFLOAD_CAPABILITIES   = 0x6,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_NIC_FLOW_TABLE_CAPABILITIES           = 0x7,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ESWITCH_FLOW_TABLE_CAPABILITIES       = 0x8,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ESWITCH_CAPABILITIES                  = 0x9,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_VECTOR_CALC_CAPABILITIES              = 0xb,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_QUALITY_OF_SERVICE_CAPABILITIES       = 0xc,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_DEBUG_CAPABILITIES                    = 0xd,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_NVME                                  = 0xe,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_DEVICE_MEMORY_CAPABILITIES            = 0xf,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_NVME_DEVICE_EMULATION_CAPABILITIES    = 0x10,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_TLS_CAPABILITIES                      = 0x11,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_DPP_CAPABILITIES                      = 0x12,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_VDPA_EMULATION_CAPABILITIES           = 0x13,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_EVENT_CAPABILITIES                    = 0x14,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_IPSEC_CAPABILITIES                    = 0x15,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_VIRTIO_NET_EMULATION_CAPABILITIES     = 0x16,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_VIRTIO_BLK_EMULATION_CAPABILITIES     = 0x17,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_HOTPLUG_CAPABILITIES                  = 0x18,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_NVMEOTCP_CAPABILITIES                 = 0x19,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_CRYPTO_CAPABILITIES                   = 0x1a,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_WQE_BASED_FLOW_TABLE_CAPABILITIES     = 0x1b,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_PARSE_GRAPH_NODE_CAPABILITIES         = 0x1c,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_SHAMPO_CAPABILITES                    = 0x1d,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_PSP_CAPABILITIES                      = 0x1e,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_MACSEC_CAPABILITIES                   = 0x1f,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_GENERAL_DEVICE_CAPABILITIES_2         = 0x20,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_UPT_DEVICE_EMULATION_CAPABILITIES     = 0x21,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_VIRTIO_FS_EMULATION_CAPABILITIES      = 0x23,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_DPA_CAPABILITIES                      = 0x24,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_PORT_SELECTION_CAPABILITIES           = 0x25,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ADV_VIRTUALIZATION_CAPABILITIES       = 0x26,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_GENERIC_DEVICE_EMULATION_CAPABILITIES = 0x27,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_ADV_RDMA_CAPABILITIES                 = 0x28,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_TRANSPORT_SERVICE_PROV_CAPABILITIES   = 0x29,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_TLP_DEVICE_EMULATION                  = 0x2a,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_CC_SERVICE_PROV_CAPABILITIES          = 0x2b,
	HCA_CAP_TYPES__QUERY_HCA_CAP_IN_OP_MOD_PASO_CAPABILITIES                     = 0x2c
};

#endif /* H_BITS_HCA_CAP_TYPES_ADB_H*/
